/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Greet: typeof import('./src/components/Greet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheTitlebar: typeof import('./src/components/TheTitlebar.vue')['default']
  }
}
